server:
  servlet:
    context-path: /mpl
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.78.206.78:3306/mybatispluslearning?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root123..
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0